### ISSUE TITLE
THE KEY CODE CAN NOT BE FOUND

### ISSUE THREAD

**Issue by Bunnybeibei** [oom-debugger/ijcai23#1]
It is bizarre that the critical code about the normalized hyperbolic model is missing but contains much-existing research. It would be very appreciated if you could update or clarify the critical codes on README.

**Comment by oom-debugger** [comment]
The key code is already in there (see below). it is a simple hyperbolic normalization layer that can be added to any model (and needs to be used with a Riemannian optimizater).

Here is an example: https://github.com/oom-debugger/ijcai23/blob/main/torch-rgcn/torch_rgcn/models.py#L339

another example: https://github.com/oom-debugger/ijcai23/blob/main/GCNII-master/model.py#L120
